# Generated by Django 2.2 on 2020-04-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200409_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
